sudo: false
language: node_js
node_js:
  - '6'
  - '7'
install:
  - npm i npminstall && npminstall
  - node t.js
script:
  - npm run ci
after_script:
  - npminstall codecov && codecov
services:
  - redis
